# Generated by Django 3.2.15 on 2024-03-13 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_client_order_orderedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedproduct',
            options={'verbose_name': 'Заказанный продукт', 'verbose_name_plural': 'Заказанные продукты'},
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена расчёта'),
        ),
    ]
