# Generated by Django 3.2.15 on 2024-04-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_strike_price_on_ordered_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'Новый заказ'), ('cooking', 'Готовится'), ('on_the_road', 'Передан курьеру'), ('delivered', 'Доставлен')], db_index=True, default='new_order', max_length=11, verbose_name='Статус заказа'),
        ),
    ]
