# Generated by Django 3.2.15 on 2024-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_processing_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('not_selected', 'Не выбрано'), ('cash', 'Наличные'), ('card', 'Электронно')], db_index=True, default='not_selected', max_length=12, verbose_name='Способ оплаты'),
        ),
    ]
