# Generated by Django 3.2.15 on 2024-04-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executing_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Исполняющий ресторан'),
        ),
    ]
